[theme]
base = "light"
primaryColor = "#FF826B"
backgroundColor = "#F4FBFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#20202B"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
